version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    container_name: backend-app

  frontend:
    build:
      context: ./frontend_new
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: frontend-app
